### ISSUE TITLE
Mapping of entity mentions from English to other languages

### ISSUE THREAD

**Issue by rathorevipul28** [samsungnlp/smiler#2]
Dear authors,
Could you please share the translations of entity mentions from English to the other languages ? We want to use that mapping to convert SmiLER dataset for our task. We need unique ids of entity mentions across languages to fix them and convert the dataset to only relation extraction task that we are working upon.

**Comment by dialogue-systems** [comment]
Unfortunately, we are not able to provide the translations of entity mentions.
